/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.apis;

import com.spotify.api.ApiHelper;
import com.spotify.api.Server;
import com.spotify.api.exceptions.ApiException;
import com.spotify.api.exceptions.Forbidden1Exception;
import com.spotify.api.exceptions.TooManyRequests1Exception;
import com.spotify.api.exceptions.Unauthorized1Exception;
import com.spotify.api.http.request.HttpMethod;
import com.spotify.api.http.response.ApiResponse;
import com.spotify.api.models.IncludeExternal;
import com.spotify.api.models.Itemtype;
import com.spotify.api.models.SearchItems;
import io.apimatic.core.ApiCall;
import io.apimatic.core.ErrorCase;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.http.request.ResponseClassType;
import java.io.IOException;
import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionException;

/**
 * This class lists all the endpoints of the groups.
 */
public final class SearchApi extends BaseApi {

    /**
     * Initializes the controller.
     * @param globalConfig    Configurations added in client.
     */
    public SearchApi(GlobalConfiguration globalConfig) {
        super(globalConfig);
    }

    /**
     * Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or
     * audiobooks that match a keyword string. Audiobooks are only available within the US, UK,
     * Canada, Ireland, New Zealand and Australia markets.
     * @param  q  Required parameter:
     * @param  type  Required parameter:
     * @param  market  Optional parameter:
     * @param  limit  Optional parameter: Example: 20
     * @param  offset  Optional parameter: Example: 0
     * @param  includeExternal  Optional parameter:
     * @return    Returns the SearchItems wrapped in ApiResponse response from the API call
     * @throws    ApiException    Represents error response from the server.
     * @throws    IOException    Signals that an I/O exception of some sort has occurred.
     */
    public ApiResponse<SearchItems> search(
            final String q,
            final List<Itemtype> type,
            final String market,
            final Integer limit,
            final Integer offset,
            final IncludeExternal includeExternal) throws ApiException, IOException {
        return prepareSearchRequest(q, type, market, limit, offset, includeExternal).execute();
    }

    /**
     * Get Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or
     * audiobooks that match a keyword string. Audiobooks are only available within the US, UK,
     * Canada, Ireland, New Zealand and Australia markets.
     * @param  q  Required parameter:
     * @param  type  Required parameter:
     * @param  market  Optional parameter:
     * @param  limit  Optional parameter: Example: 20
     * @param  offset  Optional parameter: Example: 0
     * @param  includeExternal  Optional parameter:
     * @return    Returns the SearchItems wrapped in ApiResponse response from the API call
     */
    public CompletableFuture<ApiResponse<SearchItems>> searchAsync(
            final String q,
            final List<Itemtype> type,
            final String market,
            final Integer limit,
            final Integer offset,
            final IncludeExternal includeExternal) {
        try {
            return prepareSearchRequest(q, type, market, limit, offset, includeExternal).executeAsync();
        } catch (Exception e) {
            throw new CompletionException(e);
        }
    }

    /**
     * Builds the ApiCall object for search.
     */
    private ApiCall<ApiResponse<SearchItems>, ApiException> prepareSearchRequest(
            final String q,
            final List<Itemtype> type,
            final String market,
            final Integer limit,
            final Integer offset,
            final IncludeExternal includeExternal) {
        return new ApiCall.Builder<ApiResponse<SearchItems>, ApiException>()
                .globalConfig(getGlobalConfiguration())
                .requestBuilder(requestBuilder -> requestBuilder
                        .server(Server.ENUM_DEFAULT.value())
                        .path("/search")
                        .queryParam(param -> param.key("q")
                                .value(q))
                        .queryParam(param -> param.key("type")
                                .value(Itemtype.toValue(type)))
                        .queryParam(param -> param.key("market")
                                .value(market).isRequired(false))
                        .queryParam(param -> param.key("limit")
                                .value((limit != null) ? limit : 20).isRequired(false))
                        .queryParam(param -> param.key("offset")
                                .value((offset != null) ? offset : 0).isRequired(false))
                        .queryParam(param -> param.key("include_external")
                                .value((includeExternal != null) ? includeExternal.value() : null).isRequired(false))
                        .headerParam(param -> param.key("accept").value("application/json"))
                        .withAuth(auth -> auth
                                .add("oauth_2_0"))
                        .httpMethod(HttpMethod.GET))
                .responseHandler(responseHandler -> responseHandler
                        .responseClassType(ResponseClassType.API_RESPONSE)
                        .apiResponseDeserializer(
                                response -> ApiHelper.deserialize(response, SearchItems.class))
                        .nullify404(false)
                        .localErrorCase("401",
                                 ErrorCase.setReason("Bad or expired token. This can happen if the user revoked a token or\nthe access token has expired. You should re-authenticate the user.",
                                (reason, context) -> new Unauthorized1Exception(reason, context)))
                        .localErrorCase("403",
                                 ErrorCase.setReason("Bad OAuth request (wrong consumer key, bad nonce, expired\ntimestamp...). Unfortunately, re-authenticating the user won't help here.",
                                (reason, context) -> new Forbidden1Exception(reason, context)))
                        .localErrorCase("429",
                                 ErrorCase.setReason("The app has exceeded its rate limits.",
                                (reason, context) -> new TooManyRequests1Exception(reason, context)))
                        .globalErrorCase(GLOBAL_ERROR_CASES))
                .build();
    }
}