/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models.containers;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.ObjectCodec;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonDeserializer;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.spotify.api.ApiHelper;
import com.spotify.api.models.EpisodeObject;
import com.spotify.api.models.TrackObject;
import io.apimatic.core.annotations.TypeCombinator.TypeCombinatorCase;
import java.io.IOException;
import java.util.Arrays;

/**
 * This is a container class for one-of types.
 */
@JsonDeserialize(using = CurrentlyPlayingContextObjectItem.CurrentlyPlayingContextObjectItemDeserializer.class)
public abstract class CurrentlyPlayingContextObjectItem {
    
    /**
     * This is TrackObject case.
     * @param trackObject TrackObject value for trackObject.
     * @return The TrackObjectCase object.
     */
    public static CurrentlyPlayingContextObjectItem fromTrackObject(TrackObject trackObject) {
        return trackObject == null ? null : new TrackObjectCase(trackObject);
    }

    /**
     * This is EpisodeObject case.
     * @param episodeObject EpisodeObject value for episodeObject.
     * @return The EpisodeObjectCase object.
     */
    public static CurrentlyPlayingContextObjectItem fromEpisodeObject(EpisodeObject episodeObject) {
        return episodeObject == null ? null : new EpisodeObjectCase(episodeObject);
    }

    /**
     * Method to match from the provided one-of cases.
     * @param <R> The type to return after applying callback.
     * @param cases The one-of type cases callback.
     * @return The one-of matched case.
     */
    public abstract <R> R match(Cases<R> cases);

    /**
     * This is interface for one-of cases.
     * @param <R> The type to return after applying callback.
     */
    public interface Cases<R> {
        R trackObject(TrackObject trackObject);

        R episodeObject(EpisodeObject episodeObject);
    }

    /**
     * This is a implementation class for TrackObjectCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "TrackObject")
    private static class TrackObjectCase extends CurrentlyPlayingContextObjectItem {

        @JsonValue
        private TrackObject trackObject;

        TrackObjectCase(TrackObject trackObject) {
            this.trackObject = trackObject;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.trackObject(this.trackObject);
        }

        @JsonCreator
        private TrackObjectCase(JsonNode jsonNode) throws IOException {
            this.trackObject = ApiHelper.deserialize(jsonNode,
                TrackObject.class);
        }

        @Override
        public String toString() {
            return trackObject.toString();
        }
    }

    /**
     * This is a implementation class for EpisodeObjectCase.
     */
    @JsonDeserialize(using = JsonDeserializer.None.class)
    @TypeCombinatorCase(type = "EpisodeObject")
    private static class EpisodeObjectCase extends CurrentlyPlayingContextObjectItem {

        @JsonValue
        private EpisodeObject episodeObject;

        EpisodeObjectCase(EpisodeObject episodeObject) {
            this.episodeObject = episodeObject;
        }

        @Override
        public <R> R match(Cases<R> cases) {
            return cases.episodeObject(this.episodeObject);
        }

        @JsonCreator
        private EpisodeObjectCase(JsonNode jsonNode) throws IOException {
            this.episodeObject = ApiHelper.deserialize(jsonNode,
                EpisodeObject.class);
        }

        @Override
        public String toString() {
            return episodeObject.toString();
        }
    }

    /**
     * This is a custom deserializer class for CurrentlyPlayingContextObjectItem.
     */
    protected static class CurrentlyPlayingContextObjectItemDeserializer
            extends JsonDeserializer<CurrentlyPlayingContextObjectItem> {

        @Override
        public CurrentlyPlayingContextObjectItem deserialize(JsonParser jp, DeserializationContext ctxt)
                throws IOException, JsonProcessingException {
            ObjectCodec oc = jp.getCodec();
            JsonNode node = oc.readTree(jp);
            return ApiHelper.deserialize(node, Arrays.asList(TrackObjectCase.class,
                    EpisodeObjectCase.class), true);
        }
    }

}
