/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api;

import com.spotify.api.apis.AlbumsApi;
import com.spotify.api.apis.ArtistsApi;
import com.spotify.api.apis.AudiobooksApi;
import com.spotify.api.apis.CategoriesApi;
import com.spotify.api.apis.ChaptersApi;
import com.spotify.api.apis.EpisodesApi;
import com.spotify.api.apis.GenresApi;
import com.spotify.api.apis.MarketsApi;
import com.spotify.api.apis.OauthAuthorizationApi;
import com.spotify.api.apis.PlayerApi;
import com.spotify.api.apis.PlaylistsApi;
import com.spotify.api.apis.SearchApi;
import com.spotify.api.apis.ShowsApi;
import com.spotify.api.apis.TracksApi;
import com.spotify.api.apis.UsersApi;
import com.spotify.api.authentication.AuthorizationCodeAuthManager;
import com.spotify.api.authentication.AuthorizationCodeAuthModel;
import com.spotify.api.http.client.HttpCallback;
import com.spotify.api.http.client.HttpClientConfiguration;
import com.spotify.api.http.client.ReadonlyHttpClientConfiguration;
import com.spotify.api.logging.configuration.ApiLoggingConfiguration;
import com.spotify.api.logging.configuration.ReadonlyLoggingConfiguration;
import io.apimatic.core.GlobalConfiguration;
import io.apimatic.coreinterfaces.authentication.Authentication;
import io.apimatic.coreinterfaces.compatibility.CompatibilityFactory;
import io.apimatic.coreinterfaces.http.HttpClient;
import io.apimatic.okhttpclient.adapter.OkClient;
import java.util.AbstractMap.SimpleEntry;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Consumer;
import java.util.function.Supplier;

/**
 * Gateway class for the library.
 * This class acts as a factory for Apis.
 * It holds the state of the SDK.
 */
public final class SpotifyWebApiClient implements Configuration {

    /**
     * Private store for controllers.
     */
    private AlbumsApi albums;
    private ArtistsApi artists;
    private AudiobooksApi audiobooks;
    private CategoriesApi categories;
    private ChaptersApi chapters;
    private EpisodesApi episodes;
    private GenresApi genres;
    private MarketsApi markets;
    private PlayerApi player;
    private PlaylistsApi playlists;
    private SearchApi search;
    private ShowsApi shows;
    private TracksApi tracks;
    private UsersApi users;
    private OauthAuthorizationApi oauthAuthorization;

    private static final CompatibilityFactory compatibilityFactory = new CompatibilityFactoryImpl();

    private static String userAgent = "Java-SDK/2024.3.3 (OS: {os-info}, Engine: {engine}/{engine-version})";

    /**
     * Current API environment.
     */
    private final Environment environment;

    /**
     * The HTTP Client instance to use for making HTTP requests.
     */
    private final HttpClient httpClient;

    /**
     * Http Client Configuration instance.
     */
    private final ReadonlyHttpClientConfiguration httpClientConfig;

    /**
     * Logging Configuration instance.
     */
    private final ReadonlyLoggingConfiguration loggingConfig;

    /**
     * AuthorizationCodeAuthManager.
     */
    private AuthorizationCodeAuthManager authorizationCodeAuthManager;

    /**
     * The instance of AuthorizationCodeAuthModel.
     */
    private AuthorizationCodeAuthModel authorizationCodeAuthModel;

    /**
     * Map of authentication Managers.
     */
    private Map<String, Authentication> authentications = new HashMap<String, Authentication>();

    /**
     * Callback to be called before and after the HTTP call for an endpoint is made.
     */
    private final HttpCallback httpCallback;

    private SpotifyWebApiClient(Environment environment, HttpClient httpClient,
            ReadonlyHttpClientConfiguration httpClientConfig,
            ReadonlyLoggingConfiguration loggingConfig,
            AuthorizationCodeAuthModel authorizationCodeAuthModel, HttpCallback httpCallback) {
        this.environment = environment;
        this.httpClient = httpClient;
        this.httpClientConfig = httpClientConfig;
        this.loggingConfig = loggingConfig;
        this.httpCallback = httpCallback;

        this.authorizationCodeAuthModel = authorizationCodeAuthModel;

        this.authorizationCodeAuthManager = new AuthorizationCodeAuthManager(
                authorizationCodeAuthModel);
        this.authentications.put("oauth_2_0", authorizationCodeAuthManager);

        GlobalConfiguration globalConfig = new GlobalConfiguration.Builder()
                .httpClient(httpClient).baseUri(server -> getBaseUri(server))
                .compatibilityFactory(compatibilityFactory)
                .authentication(this.authentications)
                .callback(httpCallback)
                .userAgent(userAgent)
                .loggingConfiguration(((ApiLoggingConfiguration) loggingConfig).getConfiguration())
                .build();
        this.authorizationCodeAuthManager.applyGlobalConfiguration(globalConfig);

        albums = new AlbumsApi(globalConfig);
        artists = new ArtistsApi(globalConfig);
        audiobooks = new AudiobooksApi(globalConfig);
        categories = new CategoriesApi(globalConfig);
        chapters = new ChaptersApi(globalConfig);
        episodes = new EpisodesApi(globalConfig);
        genres = new GenresApi(globalConfig);
        markets = new MarketsApi(globalConfig);
        player = new PlayerApi(globalConfig);
        playlists = new PlaylistsApi(globalConfig);
        search = new SearchApi(globalConfig);
        shows = new ShowsApi(globalConfig);
        tracks = new TracksApi(globalConfig);
        users = new UsersApi(globalConfig);
        oauthAuthorization = new OauthAuthorizationApi(globalConfig);
    }

    /**
     * Shutdown the underlying HttpClient instance.
     */
    public static void shutdown() {
        OkClient.shutdown();
    }

    /**
     * Get the instance of AlbumsApi.
     * @return albums
     */
    public AlbumsApi getAlbumsApi() {
        return albums;
    }

    /**
     * Get the instance of ArtistsApi.
     * @return artists
     */
    public ArtistsApi getArtistsApi() {
        return artists;
    }

    /**
     * Get the instance of AudiobooksApi.
     * @return audiobooks
     */
    public AudiobooksApi getAudiobooksApi() {
        return audiobooks;
    }

    /**
     * Get the instance of CategoriesApi.
     * @return categories
     */
    public CategoriesApi getCategoriesApi() {
        return categories;
    }

    /**
     * Get the instance of ChaptersApi.
     * @return chapters
     */
    public ChaptersApi getChaptersApi() {
        return chapters;
    }

    /**
     * Get the instance of EpisodesApi.
     * @return episodes
     */
    public EpisodesApi getEpisodesApi() {
        return episodes;
    }

    /**
     * Get the instance of GenresApi.
     * @return genres
     */
    public GenresApi getGenresApi() {
        return genres;
    }

    /**
     * Get the instance of MarketsApi.
     * @return markets
     */
    public MarketsApi getMarketsApi() {
        return markets;
    }

    /**
     * Get the instance of PlayerApi.
     * @return player
     */
    public PlayerApi getPlayerApi() {
        return player;
    }

    /**
     * Get the instance of PlaylistsApi.
     * @return playlists
     */
    public PlaylistsApi getPlaylistsApi() {
        return playlists;
    }

    /**
     * Get the instance of SearchApi.
     * @return search
     */
    public SearchApi getSearchApi() {
        return search;
    }

    /**
     * Get the instance of ShowsApi.
     * @return shows
     */
    public ShowsApi getShowsApi() {
        return shows;
    }

    /**
     * Get the instance of TracksApi.
     * @return tracks
     */
    public TracksApi getTracksApi() {
        return tracks;
    }

    /**
     * Get the instance of UsersApi.
     * @return users
     */
    public UsersApi getUsersApi() {
        return users;
    }

    /**
     * Get the instance of OauthAuthorizationApi.
     * @return oauthAuthorization
     */
    public OauthAuthorizationApi getOauthAuthorizationApi() {
        return oauthAuthorization;
    }

    /**
     * Current API environment.
     * @return environment
     */
    public Environment getEnvironment() {
        return environment;
    }

    /**
     * The HTTP Client instance to use for making HTTP requests.
     * @return httpClient
     */
    private HttpClient getHttpClient() {
        return httpClient;
    }

    /**
     * Http Client Configuration instance.
     * @return httpClientConfig
     */
    public ReadonlyHttpClientConfiguration getHttpClientConfig() {
        return httpClientConfig;
    }

    /**
     * Logging Configuration instance.
     * @return loggingConfig
     */
    public ReadonlyLoggingConfiguration getLoggingConfig() {
        return loggingConfig;
    }

    /**
     * The credentials to use with AuthorizationCodeAuth.
     * @return authorizationCodeAuth
     */
    public AuthorizationCodeAuth getAuthorizationCodeAuth() {
        return authorizationCodeAuthManager;
    }

    /**
     * The auth credential model for AuthorizationCodeAuth.
     * @return the instance of AuthorizationCodeAuthModel
     */
    public AuthorizationCodeAuthModel getAuthorizationCodeAuthModel() {
        return authorizationCodeAuthModel;
    }
    /**
     * The timeout to use for making HTTP requests.
     * @deprecated This method will be removed in a future version. Use
     *             {@link #getHttpClientConfig()} instead.
     *
     * @return timeout
     */
    @Deprecated
    public long timeout() {
        return httpClientConfig.getTimeout();
    }

    /**
     * Get base URI by current environment.
     * @param server Server for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(Server server) {
        Map<String, SimpleEntry<Object, Boolean>> parameters = new HashMap<>();
        StringBuilder baseUrl = new StringBuilder(environmentMapper(environment, server));
        ApiHelper.appendUrlWithTemplateParameters(baseUrl, parameters);
        return baseUrl.toString();
    }

    /**
     * Get base URI by current environment.
     * @return Processed base URI
     */
    public String getBaseUri() {
        return getBaseUri(Server.ENUM_DEFAULT);
    }


    /**
     * Get base URI by current environment.
     * 
     * @param server string for which to get the base URI
     * @return Processed base URI
     */
    public String getBaseUri(String server) {
        return getBaseUri(Server.fromString(server));
    }


    /**
     * Base URLs by environment and server aliases.
     * @param environment Environment for which to get the base URI
     * @param server Server for which to get the base URI
     * @return base URL
     */
    private static String environmentMapper(Environment environment, Server server) {
        if (environment.equals(Environment.PRODUCTION)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://api.spotify.com/v1";
            }
        }
        if (environment.equals(Environment.ENVIRONMENT2)) {
            if (server.equals(Server.ENUM_DEFAULT)) {
                return "https://accounts.spotify.com";
            }
        }
        return "https://api.spotify.com/v1";
    }

    /**
     * Converts this SpotifyWebApiClient into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SpotifyWebApiClient [" + "environment=" + environment + ", httpClientConfig="
                + httpClientConfig + ", loggingConfig=" + loggingConfig + ", authentications="
                + authentications + "]";
    }

    /**
     * Builds a new {@link SpotifyWebApiClient.Builder} object.
     * Creates the instance with the state of the current client.
     * @return a new {@link SpotifyWebApiClient.Builder} object
     */
    public Builder newBuilder() {
        Builder builder = new Builder();
        builder.environment = getEnvironment();
        builder.httpClient = getHttpClient();
        builder.authorizationCodeAuth(getAuthorizationCodeAuthModel()
                .toBuilder().build());
        builder.httpCallback = httpCallback;
        builder.httpClientConfig(() -> ((HttpClientConfiguration) httpClientConfig).newBuilder());
        builder.loggingConfig(() -> ((ApiLoggingConfiguration) loggingConfig).newBuilder());
        return builder;
    }

    /**
     * Class to build instances of {@link SpotifyWebApiClient}.
     */
    public static class Builder {

        private Environment environment = Environment.PRODUCTION;
        private HttpClient httpClient;
        private AuthorizationCodeAuthModel authorizationCodeAuthModel =
                new AuthorizationCodeAuthModel.Builder("", "", "").build();
        private HttpCallback httpCallback = null;
        private HttpClientConfiguration.Builder httpClientConfigBuilder =
                new HttpClientConfiguration.Builder();
        private ApiLoggingConfiguration.Builder loggingConfigBuilder = null;


        /**
         * Credentials setter for AuthorizationCodeAuth.
         * @param authorizationCodeAuthModel The instance of AuthorizationCodeAuthModel.
         * @return The current instance of builder.
         */
        public Builder authorizationCodeAuth(
                AuthorizationCodeAuthModel authorizationCodeAuthModel) {
            this.authorizationCodeAuthModel = authorizationCodeAuthModel;
            return this;
        }

        /**
         * Current API environment.
         * @param environment The environment for client.
         * @return Builder
         */
        public Builder environment(Environment environment) {
            this.environment = environment;
            return this;
        }

        /**
         * The timeout to use for making HTTP requests.
         * @deprecated This method will be removed in a future version. Use
         *             {@link #httpClientConfig(Consumer) httpClientConfig} instead.
         * @param timeout must be greater then 0.
         * @return Builder
         */
        @Deprecated
        public Builder timeout(long timeout) {
            this.httpClientConfigBuilder.timeout(timeout);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration, takes in an operation to be
         * performed on the builder instance of logging configuration.
         * @param action Consumer for the builder of LoggingConfiguration.
         * @return Builder
         */
        public Builder loggingConfig(Consumer<ApiLoggingConfiguration.Builder> action) {
            if (loggingConfigBuilder == null) {
                loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            }

            if (loggingConfigBuilder.build().getLogger() == null) {
                loggingConfigBuilder.useDefaultLogger();
            }

            action.accept(loggingConfigBuilder);
            return this;
        }

        /**
         * Setter for the Builder of LoggingConfiguration with Console Logging.
         *
         * @return Builder
         */
        public Builder loggingConfig() {
            loggingConfigBuilder = new ApiLoggingConfiguration.Builder();
            loggingConfigBuilder.useDefaultLogger();
            return this;
        }

		/**
		 * Private setter for the Builder of LoggingConfiguration, takes in an operation to be
		 * performed on the builder instance of logging configuration.
		 * 
		 * @param supplier Supplier for the builder of LoggingConfiguration.
		 * @return Builder
		 */
		private Builder loggingConfig(Supplier<ApiLoggingConfiguration.Builder> supplier) {
			loggingConfigBuilder = supplier.get();
			return this;
		}

        /**
         * HttpCallback.
         * @param httpCallback Callback to be called before and after the HTTP call.
         * @return Builder
         */
        public Builder httpCallback(HttpCallback httpCallback) {
            this.httpCallback = httpCallback;
            return this;
        }

        /**
         * Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param action Consumer for the builder of httpClientConfiguration.
         * @return Builder
         */
        public Builder httpClientConfig(Consumer<HttpClientConfiguration.Builder> action) {
            action.accept(httpClientConfigBuilder);
            return this;
        }

        /**
         * Private Setter for the Builder of httpClientConfiguration, takes in an operation to be performed
         * on the builder instance of HTTP client configuration.
         * 
         * @param supplier Supplier for the builder of httpClientConfiguration.
         * @return Builder
         */
        private Builder httpClientConfig(Supplier<HttpClientConfiguration.Builder> supplier) {
            httpClientConfigBuilder = supplier.get();
            return this;
        }

        /**
         * Builds a new SpotifyWebApiClient object using the set fields.
         * @return SpotifyWebApiClient
         */
        public SpotifyWebApiClient build() {
            HttpClientConfiguration httpClientConfig = httpClientConfigBuilder.build();
            ReadonlyLoggingConfiguration loggingConfig = loggingConfigBuilder != null ? loggingConfigBuilder.build() 
                    : new ApiLoggingConfiguration.Builder().build();
            httpClient = new OkClient(httpClientConfig.getConfiguration(), compatibilityFactory);

            return new SpotifyWebApiClient(environment, httpClient, httpClientConfig, loggingConfig,
                    authorizationCodeAuthModel, httpCallback);
        }
    }
}