/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for AlbumRestrictionObject type.
 */
public class AlbumRestrictionObject {
    private Reason reason;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public AlbumRestrictionObject() {
    }

    /**
     * Initialization constructor.
     * @param  reason  Reason value for reason.
     */
    public AlbumRestrictionObject(
            Reason reason) {
        this.reason = reason;
    }

    /**
     * Getter for Reason.
     * @return Returns the Reason
     */
    @JsonGetter("reason")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Reason getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * @param reason Value for Reason
     */
    @JsonSetter("reason")
    public void setReason(Reason reason) {
        this.reason = reason;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this AlbumRestrictionObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AlbumRestrictionObject [" + "reason=" + reason + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link AlbumRestrictionObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AlbumRestrictionObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .reason(getReason());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link AlbumRestrictionObject}.
     */
    public static class Builder {
        private Reason reason;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for reason.
         * @param  reason  Reason value for reason.
         * @return Builder
         */
        public Builder reason(Reason reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link AlbumRestrictionObject} object using the set fields.
         * @return {@link AlbumRestrictionObject}
         */
        public AlbumRestrictionObject build() {
            AlbumRestrictionObject model =
                    new AlbumRestrictionObject(reason);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
