/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for CursorPagingSimplifiedArtistObject type.
 */
public class CursorPagingSimplifiedArtistObject {
    private String href;
    private Integer limit;
    private String next;
    private CursorObject cursors;
    private Integer total;
    private List<ArtistObject> items;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public CursorPagingSimplifiedArtistObject() {
    }

    /**
     * Initialization constructor.
     * @param  href  String value for href.
     * @param  limit  Integer value for limit.
     * @param  next  String value for next.
     * @param  cursors  CursorObject value for cursors.
     * @param  total  Integer value for total.
     * @param  items  List of ArtistObject value for items.
     */
    public CursorPagingSimplifiedArtistObject(
            String href,
            Integer limit,
            String next,
            CursorObject cursors,
            Integer total,
            List<ArtistObject> items) {
        this.href = href;
        this.limit = limit;
        this.next = next;
        this.cursors = cursors;
        this.total = total;
        this.items = items;
    }

    /**
     * Getter for Href.
     * A link to the Web API endpoint returning the full result of the request.
     * @return Returns the String
     */
    @JsonGetter("href")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHref() {
        return href;
    }

    /**
     * Setter for Href.
     * A link to the Web API endpoint returning the full result of the request.
     * @param href Value for String
     */
    @JsonSetter("href")
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * Getter for Limit.
     * The maximum number of items in the response (as set in the query or by default).
     * @return Returns the Integer
     */
    @JsonGetter("limit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getLimit() {
        return limit;
    }

    /**
     * Setter for Limit.
     * The maximum number of items in the response (as set in the query or by default).
     * @param limit Value for Integer
     */
    @JsonSetter("limit")
    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    /**
     * Getter for Next.
     * URL to the next page of items. ( `null` if none)
     * @return Returns the String
     */
    @JsonGetter("next")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getNext() {
        return next;
    }

    /**
     * Setter for Next.
     * URL to the next page of items. ( `null` if none)
     * @param next Value for String
     */
    @JsonSetter("next")
    public void setNext(String next) {
        this.next = next;
    }

    /**
     * Getter for Cursors.
     * @return Returns the CursorObject
     */
    @JsonGetter("cursors")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public CursorObject getCursors() {
        return cursors;
    }

    /**
     * Setter for Cursors.
     * @param cursors Value for CursorObject
     */
    @JsonSetter("cursors")
    public void setCursors(CursorObject cursors) {
        this.cursors = cursors;
    }

    /**
     * Getter for Total.
     * The total number of items available to return.
     * @return Returns the Integer
     */
    @JsonGetter("total")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTotal() {
        return total;
    }

    /**
     * Setter for Total.
     * The total number of items available to return.
     * @param total Value for Integer
     */
    @JsonSetter("total")
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * Getter for Items.
     * @return Returns the List of ArtistObject
     */
    @JsonGetter("items")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<ArtistObject> getItems() {
        return items;
    }

    /**
     * Setter for Items.
     * @param items Value for List of ArtistObject
     */
    @JsonSetter("items")
    public void setItems(List<ArtistObject> items) {
        this.items = items;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this CursorPagingSimplifiedArtistObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CursorPagingSimplifiedArtistObject [" + "href=" + href + ", limit=" + limit
                + ", next=" + next + ", cursors=" + cursors + ", total=" + total + ", items="
                + items + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link CursorPagingSimplifiedArtistObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CursorPagingSimplifiedArtistObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .href(getHref())
                .limit(getLimit())
                .next(getNext())
                .cursors(getCursors())
                .total(getTotal())
                .items(getItems());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link CursorPagingSimplifiedArtistObject}.
     */
    public static class Builder {
        private String href;
        private Integer limit;
        private String next;
        private CursorObject cursors;
        private Integer total;
        private List<ArtistObject> items;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for href.
         * @param  href  String value for href.
         * @return Builder
         */
        public Builder href(String href) {
            this.href = href;
            return this;
        }

        /**
         * Setter for limit.
         * @param  limit  Integer value for limit.
         * @return Builder
         */
        public Builder limit(Integer limit) {
            this.limit = limit;
            return this;
        }

        /**
         * Setter for next.
         * @param  next  String value for next.
         * @return Builder
         */
        public Builder next(String next) {
            this.next = next;
            return this;
        }

        /**
         * Setter for cursors.
         * @param  cursors  CursorObject value for cursors.
         * @return Builder
         */
        public Builder cursors(CursorObject cursors) {
            this.cursors = cursors;
            return this;
        }

        /**
         * Setter for total.
         * @param  total  Integer value for total.
         * @return Builder
         */
        public Builder total(Integer total) {
            this.total = total;
            return this;
        }

        /**
         * Setter for items.
         * @param  items  List of ArtistObject value for items.
         * @return Builder
         */
        public Builder items(List<ArtistObject> items) {
            this.items = items;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link CursorPagingSimplifiedArtistObject} object using the set fields.
         * @return {@link CursorPagingSimplifiedArtistObject}
         */
        public CursorPagingSimplifiedArtistObject build() {
            CursorPagingSimplifiedArtistObject model =
                    new CursorPagingSimplifiedArtistObject(href, limit, next, cursors, total,
                            items);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
