/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for EpisodeRestrictionObject type.
 */
public class EpisodeRestrictionObject {
    private String reason;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public EpisodeRestrictionObject() {
    }

    /**
     * Initialization constructor.
     * @param  reason  String value for reason.
     */
    public EpisodeRestrictionObject(
            String reason) {
        this.reason = reason;
    }

    /**
     * Getter for Reason.
     * The reason for the restriction. Supported values: - `market` - The content item is not
     * available in the given market. - `product` - The content item is not available for the user's
     * subscription type. - `explicit` - The content item is explicit and the user's account is set
     * to not play explicit content. Additional reasons may be added in the future. **Note**: If you
     * use this field, make sure that your application safely handles unknown values.
     * @return Returns the String
     */
    @JsonGetter("reason")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * The reason for the restriction. Supported values: - `market` - The content item is not
     * available in the given market. - `product` - The content item is not available for the user's
     * subscription type. - `explicit` - The content item is explicit and the user's account is set
     * to not play explicit content. Additional reasons may be added in the future. **Note**: If you
     * use this field, make sure that your application safely handles unknown values.
     * @param reason Value for String
     */
    @JsonSetter("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this EpisodeRestrictionObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EpisodeRestrictionObject [" + "reason=" + reason + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link EpisodeRestrictionObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EpisodeRestrictionObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .reason(getReason());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link EpisodeRestrictionObject}.
     */
    public static class Builder {
        private String reason;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for reason.
         * @param  reason  String value for reason.
         * @return Builder
         */
        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link EpisodeRestrictionObject} object using the set fields.
         * @return {@link EpisodeRestrictionObject}
         */
        public EpisodeRestrictionObject build() {
            EpisodeRestrictionObject model =
                    new EpisodeRestrictionObject(reason);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
