/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ErrorObject type.
 */
public class ErrorObject {
    private int status;
    private String message;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ErrorObject() {
    }

    /**
     * Initialization constructor.
     * @param  status  int value for status.
     * @param  message  String value for message.
     */
    public ErrorObject(
            int status,
            String message) {
        this.status = status;
        this.message = message;
    }

    /**
     * Getter for Status.
     * The HTTP status code (also returned in the response header; see [Response Status
     * Codes](https://developer.spotify.com/documentation/web-api/concepts/api-calls#response-status-codes)
     * for more information).
     * @return Returns the int
     */
    @JsonGetter("status")
    public int getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * The HTTP status code (also returned in the response header; see [Response Status
     * Codes](https://developer.spotify.com/documentation/web-api/concepts/api-calls#response-status-codes)
     * for more information).
     * @param status Value for int
     */
    @JsonSetter("status")
    public void setStatus(int status) {
        this.status = status;
    }

    /**
     * Getter for Message.
     * A short description of the cause of the error.
     * @return Returns the String
     */
    @JsonGetter("message")
    public String getMessage() {
        return message;
    }

    /**
     * Setter for Message.
     * A short description of the cause of the error.
     * @param message Value for String
     */
    @JsonSetter("message")
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ErrorObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ErrorObject [" + "status=" + status + ", message=" + message
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ErrorObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ErrorObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(status, message);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ErrorObject}.
     */
    public static class Builder {
        private int status;
        private String message;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  status  int value for status.
         * @param  message  String value for message.
         */
        public Builder(int status, String message) {
            this.status = status;
            this.message = message;
        }

        /**
         * Setter for status.
         * @param  status  int value for status.
         * @return Builder
         */
        public Builder status(int status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for message.
         * @param  message  String value for message.
         * @return Builder
         */
        public Builder message(String message) {
            this.message = message;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ErrorObject} object using the set fields.
         * @return {@link ErrorObject}
         */
        public ErrorObject build() {
            ErrorObject model =
                    new ErrorObject(status, message);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
