/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ExternalUrlObject type.
 */
public class ExternalUrlObject {
    private String spotify;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ExternalUrlObject() {
    }

    /**
     * Initialization constructor.
     * @param  spotify  String value for spotify.
     */
    public ExternalUrlObject(
            String spotify) {
        this.spotify = spotify;
    }

    /**
     * Getter for Spotify.
     * The [Spotify
     * URL](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for the
     * object.
     * @return Returns the String
     */
    @JsonGetter("spotify")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSpotify() {
        return spotify;
    }

    /**
     * Setter for Spotify.
     * The [Spotify
     * URL](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for the
     * object.
     * @param spotify Value for String
     */
    @JsonSetter("spotify")
    public void setSpotify(String spotify) {
        this.spotify = spotify;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ExternalUrlObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ExternalUrlObject [" + "spotify=" + spotify + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ExternalUrlObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ExternalUrlObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .spotify(getSpotify());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ExternalUrlObject}.
     */
    public static class Builder {
        private String spotify;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for spotify.
         * @param  spotify  String value for spotify.
         * @return Builder
         */
        public Builder spotify(String spotify) {
            this.spotify = spotify;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ExternalUrlObject} object using the set fields.
         * @return {@link ExternalUrlObject}
         */
        public ExternalUrlObject build() {
            ExternalUrlObject model =
                    new ExternalUrlObject(spotify);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
