/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for FollowersObject type.
 */
public class FollowersObject {
    private OptionalNullable<String> href;
    private Integer total;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public FollowersObject() {
    }

    /**
     * Initialization constructor.
     * @param  href  String value for href.
     * @param  total  Integer value for total.
     */
    public FollowersObject(
            String href,
            Integer total) {
        this.href = OptionalNullable.of(href);
        this.total = total;
    }

    /**
     * Initialization constructor.
     * @param  href  String value for href.
     * @param  total  Integer value for total.
     */

    protected FollowersObject(OptionalNullable<String> href, Integer total) {
        this.href = href;
        this.total = total;
    }

    /**
     * Internal Getter for Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     * @return Returns the Internal String
     */
    @JsonGetter("href")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetHref() {
        return this.href;
    }

    /**
     * Getter for Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     * @return Returns the String
     */
    public String getHref() {
        return OptionalNullable.getFrom(href);
    }

    /**
     * Setter for Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     * @param href Value for String
     */
    @JsonSetter("href")
    public void setHref(String href) {
        this.href = OptionalNullable.of(href);
    }

    /**
     * UnSetter for Href.
     * This will always be set to null, as the Web API does not support it at the moment.
     */
    public void unsetHref() {
        href = null;
    }

    /**
     * Getter for Total.
     * The total number of followers.
     * @return Returns the Integer
     */
    @JsonGetter("total")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getTotal() {
        return total;
    }

    /**
     * Setter for Total.
     * The total number of followers.
     * @param total Value for Integer
     */
    @JsonSetter("total")
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this FollowersObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "FollowersObject [" + "href=" + href + ", total=" + total + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link FollowersObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link FollowersObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .total(getTotal());
        builder.href = internalGetHref();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link FollowersObject}.
     */
    public static class Builder {
        private OptionalNullable<String> href;
        private Integer total;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for href.
         * @param  href  String value for href.
         * @return Builder
         */
        public Builder href(String href) {
            this.href = OptionalNullable.of(href);
            return this;
        }

        /**
         * UnSetter for href.
         * @return Builder
         */
        public Builder unsetHref() {
            href = null;
            return this;
        }

        /**
         * Setter for total.
         * @param  total  Integer value for total.
         * @return Builder
         */
        public Builder total(Integer total) {
            this.total = total;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link FollowersObject} object using the set fields.
         * @return {@link FollowersObject}
         */
        public FollowersObject build() {
            FollowersObject model =
                    new FollowersObject(href, total);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
