/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for ImageObject type.
 */
public class ImageObject {
    private String url;
    private Integer height;
    private Integer width;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ImageObject() {
    }

    /**
     * Initialization constructor.
     * @param  url  String value for url.
     * @param  height  Integer value for height.
     * @param  width  Integer value for width.
     */
    public ImageObject(
            String url,
            Integer height,
            Integer width) {
        this.url = url;
        this.height = height;
        this.width = width;
    }

    /**
     * Getter for Url.
     * The source URL of the image.
     * @return Returns the String
     */
    @JsonGetter("url")
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * The source URL of the image.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for Height.
     * The image height in pixels.
     * @return Returns the Integer
     */
    @JsonGetter("height")
    public Integer getHeight() {
        return height;
    }

    /**
     * Setter for Height.
     * The image height in pixels.
     * @param height Value for Integer
     */
    @JsonSetter("height")
    public void setHeight(Integer height) {
        this.height = height;
    }

    /**
     * Getter for Width.
     * The image width in pixels.
     * @return Returns the Integer
     */
    @JsonGetter("width")
    public Integer getWidth() {
        return width;
    }

    /**
     * Setter for Width.
     * The image width in pixels.
     * @param width Value for Integer
     */
    @JsonSetter("width")
    public void setWidth(Integer width) {
        this.width = width;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ImageObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ImageObject [" + "url=" + url + ", height=" + height + ", width=" + width
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ImageObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ImageObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(url, height, width);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ImageObject}.
     */
    public static class Builder {
        private String url;
        private Integer height;
        private Integer width;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  url  String value for url.
         * @param  height  Integer value for height.
         * @param  width  Integer value for width.
         */
        public Builder(String url, Integer height, Integer width) {
            this.url = url;
            this.height = height;
            this.width = width;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for height.
         * @param  height  Integer value for height.
         * @return Builder
         */
        public Builder height(Integer height) {
            this.height = height;
            return this;
        }

        /**
         * Setter for width.
         * @param  width  Integer value for width.
         * @return Builder
         */
        public Builder width(Integer width) {
            this.width = width;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ImageObject} object using the set fields.
         * @return {@link ImageObject}
         */
        public ImageObject build() {
            ImageObject model =
                    new ImageObject(url, height, width);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
