/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.TreeMap;

/**
 * Itemtype to be used.
 */
public enum Itemtype {
    ALBUM,

    ARTIST,

    PLAYLIST,

    TRACK,

    SHOW,

    EPISODE,

    AUDIOBOOK;

    private static TreeMap<String, Itemtype> valueMap = new TreeMap<>();
    private String value;

    static {
        ALBUM.value = "album";
        ARTIST.value = "artist";
        PLAYLIST.value = "playlist";
        TRACK.value = "track";
        SHOW.value = "show";
        EPISODE.value = "episode";
        AUDIOBOOK.value = "audiobook";

        valueMap.put("album", ALBUM);
        valueMap.put("artist", ARTIST);
        valueMap.put("playlist", PLAYLIST);
        valueMap.put("track", TRACK);
        valueMap.put("show", SHOW);
        valueMap.put("episode", EPISODE);
        valueMap.put("audiobook", AUDIOBOOK);
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     * @throws IOException when provided value is not mapped to any enum member.
     */
    @JsonCreator
    public static Itemtype constructFromString(String toConvert) throws IOException {
        Itemtype enumValue = fromString(toConvert);
        if (enumValue == null) {
            throw new IOException("Unable to create enum instance with value: " + toConvert);
        }
        return enumValue;
    }

    /**
     * Returns the enum member associated with the given string value.
     * @param toConvert String value to get enum member.
     * @return The enum member against the given string value.
     */
    public static Itemtype fromString(String toConvert) {
        return valueMap.get(toConvert);
    }

    /**
     * Returns the string value associated with the enum member.
     * @return The string value against enum member.
     */
    @JsonValue
    public String value() {
        return value;
    }
        
    /**
     * Get string representation of this enum.
     */
    @Override
    public String toString() {
        return value.toString();
    }

    /**
     * Convert list of Itemtype values to list of string values.
     * @param toConvert The list of Itemtype values to convert.
     * @return List of representative string values.
     */
    public static List<String> toValue(List<Itemtype> toConvert) {
        if (toConvert == null) {
            return null;
        }
        List<String> convertedValues = new ArrayList<>();
        for (Itemtype enumValue : toConvert) {
            convertedValues.add(enumValue.value);
        }
        return convertedValues;
    }
} 