/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ManyEpisodes type.
 */
public class ManyEpisodes {
    private List<EpisodeObject> episodes;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ManyEpisodes() {
    }

    /**
     * Initialization constructor.
     * @param  episodes  List of EpisodeObject value for episodes.
     */
    public ManyEpisodes(
            List<EpisodeObject> episodes) {
        this.episodes = episodes;
    }

    /**
     * Getter for Episodes.
     * @return Returns the List of EpisodeObject
     */
    @JsonGetter("episodes")
    public List<EpisodeObject> getEpisodes() {
        return episodes;
    }

    /**
     * Setter for Episodes.
     * @param episodes Value for List of EpisodeObject
     */
    @JsonSetter("episodes")
    public void setEpisodes(List<EpisodeObject> episodes) {
        this.episodes = episodes;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ManyEpisodes into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyEpisodes [" + "episodes=" + episodes + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ManyEpisodes.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyEpisodes.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(episodes);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ManyEpisodes}.
     */
    public static class Builder {
        private List<EpisodeObject> episodes;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  episodes  List of EpisodeObject value for episodes.
         */
        public Builder(List<EpisodeObject> episodes) {
            this.episodes = episodes;
        }

        /**
         * Setter for episodes.
         * @param  episodes  List of EpisodeObject value for episodes.
         * @return Builder
         */
        public Builder episodes(List<EpisodeObject> episodes) {
            this.episodes = episodes;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ManyEpisodes} object using the set fields.
         * @return {@link ManyEpisodes}
         */
        public ManyEpisodes build() {
            ManyEpisodes model =
                    new ManyEpisodes(episodes);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
