/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ManySimplifiedShows type.
 */
public class ManySimplifiedShows {
    private List<ShowBase> shows;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ManySimplifiedShows() {
    }

    /**
     * Initialization constructor.
     * @param  shows  List of ShowBase value for shows.
     */
    public ManySimplifiedShows(
            List<ShowBase> shows) {
        this.shows = shows;
    }

    /**
     * Getter for Shows.
     * @return Returns the List of ShowBase
     */
    @JsonGetter("shows")
    public List<ShowBase> getShows() {
        return shows;
    }

    /**
     * Setter for Shows.
     * @param shows Value for List of ShowBase
     */
    @JsonSetter("shows")
    public void setShows(List<ShowBase> shows) {
        this.shows = shows;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ManySimplifiedShows into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManySimplifiedShows [" + "shows=" + shows + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ManySimplifiedShows.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManySimplifiedShows.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(shows);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ManySimplifiedShows}.
     */
    public static class Builder {
        private List<ShowBase> shows;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  shows  List of ShowBase value for shows.
         */
        public Builder(List<ShowBase> shows) {
            this.shows = shows;
        }

        /**
         * Setter for shows.
         * @param  shows  List of ShowBase value for shows.
         * @return Builder
         */
        public Builder shows(List<ShowBase> shows) {
            this.shows = shows;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ManySimplifiedShows} object using the set fields.
         * @return {@link ManySimplifiedShows}
         */
        public ManySimplifiedShows build() {
            ManySimplifiedShows model =
                    new ManySimplifiedShows(shows);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
