/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ManyGenres type.
 */
public class ManyGenres {
    private List<String> genres;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ManyGenres() {
    }

    /**
     * Initialization constructor.
     * @param  genres  List of String value for genres.
     */
    public ManyGenres(
            List<String> genres) {
        this.genres = genres;
    }

    /**
     * Getter for Genres.
     * @return Returns the List of String
     */
    @JsonGetter("genres")
    public List<String> getGenres() {
        return genres;
    }

    /**
     * Setter for Genres.
     * @param genres Value for List of String
     */
    @JsonSetter("genres")
    public void setGenres(List<String> genres) {
        this.genres = genres;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ManyGenres into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyGenres [" + "genres=" + genres + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ManyGenres.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyGenres.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(genres);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ManyGenres}.
     */
    public static class Builder {
        private List<String> genres;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  genres  List of String value for genres.
         */
        public Builder(List<String> genres) {
            this.genres = genres;
        }

        /**
         * Setter for genres.
         * @param  genres  List of String value for genres.
         * @return Builder
         */
        public Builder genres(List<String> genres) {
            this.genres = genres;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ManyGenres} object using the set fields.
         * @return {@link ManyGenres}
         */
        public ManyGenres build() {
            ManyGenres model =
                    new ManyGenres(genres);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
