/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ManyTracks type.
 */
public class ManyTracks {
    private List<TrackObject> tracks;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ManyTracks() {
    }

    /**
     * Initialization constructor.
     * @param  tracks  List of TrackObject value for tracks.
     */
    public ManyTracks(
            List<TrackObject> tracks) {
        this.tracks = tracks;
    }

    /**
     * Getter for Tracks.
     * @return Returns the List of TrackObject
     */
    @JsonGetter("tracks")
    public List<TrackObject> getTracks() {
        return tracks;
    }

    /**
     * Setter for Tracks.
     * @param tracks Value for List of TrackObject
     */
    @JsonSetter("tracks")
    public void setTracks(List<TrackObject> tracks) {
        this.tracks = tracks;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ManyTracks into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyTracks [" + "tracks=" + tracks + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ManyTracks.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyTracks.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(tracks);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ManyTracks}.
     */
    public static class Builder {
        private List<TrackObject> tracks;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  tracks  List of TrackObject value for tracks.
         */
        public Builder(List<TrackObject> tracks) {
            this.tracks = tracks;
        }

        /**
         * Setter for tracks.
         * @param  tracks  List of TrackObject value for tracks.
         * @return Builder
         */
        public Builder tracks(List<TrackObject> tracks) {
            this.tracks = tracks;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ManyTracks} object using the set fields.
         * @return {@link ManyTracks}
         */
        public ManyTracks build() {
            ManyTracks model =
                    new ManyTracks(tracks);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
