/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ManyAudiobooks type.
 */
public class ManyAudiobooks {
    private List<AudiobookObject> audiobooks;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ManyAudiobooks() {
    }

    /**
     * Initialization constructor.
     * @param  audiobooks  List of AudiobookObject value for audiobooks.
     */
    public ManyAudiobooks(
            List<AudiobookObject> audiobooks) {
        this.audiobooks = audiobooks;
    }

    /**
     * Getter for Audiobooks.
     * @return Returns the List of AudiobookObject
     */
    @JsonGetter("audiobooks")
    public List<AudiobookObject> getAudiobooks() {
        return audiobooks;
    }

    /**
     * Setter for Audiobooks.
     * @param audiobooks Value for List of AudiobookObject
     */
    @JsonSetter("audiobooks")
    public void setAudiobooks(List<AudiobookObject> audiobooks) {
        this.audiobooks = audiobooks;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ManyAudiobooks into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyAudiobooks [" + "audiobooks=" + audiobooks + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ManyAudiobooks.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyAudiobooks.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(audiobooks);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ManyAudiobooks}.
     */
    public static class Builder {
        private List<AudiobookObject> audiobooks;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  audiobooks  List of AudiobookObject value for audiobooks.
         */
        public Builder(List<AudiobookObject> audiobooks) {
            this.audiobooks = audiobooks;
        }

        /**
         * Setter for audiobooks.
         * @param  audiobooks  List of AudiobookObject value for audiobooks.
         * @return Builder
         */
        public Builder audiobooks(List<AudiobookObject> audiobooks) {
            this.audiobooks = audiobooks;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ManyAudiobooks} object using the set fields.
         * @return {@link ManyAudiobooks}
         */
        public ManyAudiobooks build() {
            ManyAudiobooks model =
                    new ManyAudiobooks(audiobooks);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
