/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for ManyArtists type.
 */
public class ManyArtists {
    private List<ArtistObject> artists;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public ManyArtists() {
    }

    /**
     * Initialization constructor.
     * @param  artists  List of ArtistObject value for artists.
     */
    public ManyArtists(
            List<ArtistObject> artists) {
        this.artists = artists;
    }

    /**
     * Getter for Artists.
     * @return Returns the List of ArtistObject
     */
    @JsonGetter("artists")
    public List<ArtistObject> getArtists() {
        return artists;
    }

    /**
     * Setter for Artists.
     * @param artists Value for List of ArtistObject
     */
    @JsonSetter("artists")
    public void setArtists(List<ArtistObject> artists) {
        this.artists = artists;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this ManyArtists into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManyArtists [" + "artists=" + artists + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link ManyArtists.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManyArtists.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(artists);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link ManyArtists}.
     */
    public static class Builder {
        private List<ArtistObject> artists;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  artists  List of ArtistObject value for artists.
         */
        public Builder(List<ArtistObject> artists) {
            this.artists = artists;
        }

        /**
         * Setter for artists.
         * @param  artists  List of ArtistObject value for artists.
         * @return Builder
         */
        public Builder artists(List<ArtistObject> artists) {
            this.artists = artists;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link ManyArtists} object using the set fields.
         * @return {@link ManyArtists}
         */
        public ManyArtists build() {
            ManyArtists model =
                    new ManyArtists(artists);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
