/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for MePlayerRequest type.
 */
public class MePlayerRequest {
    private List<String> deviceIds;
    private Boolean play;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public MePlayerRequest() {
    }

    /**
     * Initialization constructor.
     * @param  deviceIds  List of String value for deviceIds.
     * @param  play  Boolean value for play.
     */
    public MePlayerRequest(
            List<String> deviceIds,
            Boolean play) {
        this.deviceIds = deviceIds;
        this.play = play;
    }

    /**
     * Getter for DeviceIds.
     * A JSON array containing the ID of the device on which playback should be
     * started/transferred.&lt;br/&gt;For example:`{device_ids:["74ASZWbe4lXaubB36ztrGX"]}`&lt;br/&gt;_**Note**:
     * Although an array is accepted, only a single device_id is currently supported. Supplying more
     * than one will return `400 Bad Request`_
     * @return Returns the List of String
     */
    @JsonGetter("device_ids")
    public List<String> getDeviceIds() {
        return deviceIds;
    }

    /**
     * Setter for DeviceIds.
     * A JSON array containing the ID of the device on which playback should be
     * started/transferred.&lt;br/&gt;For example:`{device_ids:["74ASZWbe4lXaubB36ztrGX"]}`&lt;br/&gt;_**Note**:
     * Although an array is accepted, only a single device_id is currently supported. Supplying more
     * than one will return `400 Bad Request`_
     * @param deviceIds Value for List of String
     */
    @JsonSetter("device_ids")
    public void setDeviceIds(List<String> deviceIds) {
        this.deviceIds = deviceIds;
    }

    /**
     * Getter for Play.
     * **true**: ensure playback happens on new device.&lt;br/&gt;**false** or not provided: keep the
     * current playback state.
     * @return Returns the Boolean
     */
    @JsonGetter("play")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPlay() {
        return play;
    }

    /**
     * Setter for Play.
     * **true**: ensure playback happens on new device.&lt;br/&gt;**false** or not provided: keep the
     * current playback state.
     * @param play Value for Boolean
     */
    @JsonSetter("play")
    public void setPlay(Boolean play) {
        this.play = play;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this MePlayerRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "MePlayerRequest [" + "deviceIds=" + deviceIds + ", play=" + play
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link MePlayerRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link MePlayerRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(deviceIds)
                .play(getPlay());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link MePlayerRequest}.
     */
    public static class Builder {
        private List<String> deviceIds;
        private Boolean play;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  deviceIds  List of String value for deviceIds.
         */
        public Builder(List<String> deviceIds) {
            this.deviceIds = deviceIds;
        }

        /**
         * Setter for deviceIds.
         * @param  deviceIds  List of String value for deviceIds.
         * @return Builder
         */
        public Builder deviceIds(List<String> deviceIds) {
            this.deviceIds = deviceIds;
            return this;
        }

        /**
         * Setter for play.
         * @param  play  Boolean value for play.
         * @return Builder
         */
        public Builder play(Boolean play) {
            this.play = play;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link MePlayerRequest} object using the set fields.
         * @return {@link MePlayerRequest}
         */
        public MePlayerRequest build() {
            MePlayerRequest model =
                    new MePlayerRequest(deviceIds, play);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
