/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.types.OptionalNullable;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PlaylistOwnerObject type.
 */
public class PlaylistOwnerObject {
    private ExternalUrlObject externalUrls;
    private FollowersObject followers;
    private String href;
    private String id;
    private Type4 type;
    private String uri;
    private OptionalNullable<String> displayName;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaylistOwnerObject() {
    }

    /**
     * Initialization constructor.
     * @param  externalUrls  ExternalUrlObject value for externalUrls.
     * @param  followers  FollowersObject value for followers.
     * @param  href  String value for href.
     * @param  id  String value for id.
     * @param  type  Type4 value for type.
     * @param  uri  String value for uri.
     * @param  displayName  String value for displayName.
     */
    public PlaylistOwnerObject(
            ExternalUrlObject externalUrls,
            FollowersObject followers,
            String href,
            String id,
            Type4 type,
            String uri,
            String displayName) {
        this.externalUrls = externalUrls;
        this.followers = followers;
        this.href = href;
        this.id = id;
        this.type = type;
        this.uri = uri;
        this.displayName = OptionalNullable.of(displayName);
    }

    /**
     * Initialization constructor.
     * @param  externalUrls  ExternalUrlObject value for externalUrls.
     * @param  followers  FollowersObject value for followers.
     * @param  href  String value for href.
     * @param  id  String value for id.
     * @param  type  Type4 value for type.
     * @param  uri  String value for uri.
     * @param  displayName  String value for displayName.
     */

    protected PlaylistOwnerObject(ExternalUrlObject externalUrls, FollowersObject followers,
            String href, String id, Type4 type, String uri,
            OptionalNullable<String> displayName) {
        this.externalUrls = externalUrls;
        this.followers = followers;
        this.href = href;
        this.id = id;
        this.type = type;
        this.uri = uri;
        this.displayName = displayName;
    }

    /**
     * Getter for ExternalUrls.
     * @return Returns the ExternalUrlObject
     */
    @JsonGetter("external_urls")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ExternalUrlObject getExternalUrls() {
        return externalUrls;
    }

    /**
     * Setter for ExternalUrls.
     * @param externalUrls Value for ExternalUrlObject
     */
    @JsonSetter("external_urls")
    public void setExternalUrls(ExternalUrlObject externalUrls) {
        this.externalUrls = externalUrls;
    }

    /**
     * Getter for Followers.
     * @return Returns the FollowersObject
     */
    @JsonGetter("followers")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public FollowersObject getFollowers() {
        return followers;
    }

    /**
     * Setter for Followers.
     * @param followers Value for FollowersObject
     */
    @JsonSetter("followers")
    public void setFollowers(FollowersObject followers) {
        this.followers = followers;
    }

    /**
     * Getter for Href.
     * A link to the Web API endpoint for this user.
     * @return Returns the String
     */
    @JsonGetter("href")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getHref() {
        return href;
    }

    /**
     * Setter for Href.
     * A link to the Web API endpoint for this user.
     * @param href Value for String
     */
    @JsonSetter("href")
    public void setHref(String href) {
        this.href = href;
    }

    /**
     * Getter for Id.
     * The [Spotify user
     * ID](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for this
     * user.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The [Spotify user
     * ID](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for this
     * user.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Type.
     * @return Returns the Type4
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Type4 getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for Type4
     */
    @JsonSetter("type")
    public void setType(Type4 type) {
        this.type = type;
    }

    /**
     * Getter for Uri.
     * The [Spotify
     * URI](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for this
     * user.
     * @return Returns the String
     */
    @JsonGetter("uri")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUri() {
        return uri;
    }

    /**
     * Setter for Uri.
     * The [Spotify
     * URI](https://developer.spotify.com/documentation/web-api/concepts/spotify-uris-ids) for this
     * user.
     * @param uri Value for String
     */
    @JsonSetter("uri")
    public void setUri(String uri) {
        this.uri = uri;
    }

    /**
     * Internal Getter for DisplayName.
     * The name displayed on the user's profile. `null` if not available.
     * @return Returns the Internal String
     */
    @JsonGetter("display_name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = OptionalNullable.Serializer.class)
    protected OptionalNullable<String> internalGetDisplayName() {
        return this.displayName;
    }

    /**
     * Getter for DisplayName.
     * The name displayed on the user's profile. `null` if not available.
     * @return Returns the String
     */
    public String getDisplayName() {
        return OptionalNullable.getFrom(displayName);
    }

    /**
     * Setter for DisplayName.
     * The name displayed on the user's profile. `null` if not available.
     * @param displayName Value for String
     */
    @JsonSetter("display_name")
    public void setDisplayName(String displayName) {
        this.displayName = OptionalNullable.of(displayName);
    }

    /**
     * UnSetter for DisplayName.
     * The name displayed on the user's profile. `null` if not available.
     */
    public void unsetDisplayName() {
        displayName = null;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaylistOwnerObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaylistOwnerObject [" + "externalUrls=" + externalUrls + ", followers=" + followers
                + ", href=" + href + ", id=" + id + ", type=" + type + ", uri=" + uri
                + ", displayName=" + displayName + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link PlaylistOwnerObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaylistOwnerObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .externalUrls(getExternalUrls())
                .followers(getFollowers())
                .href(getHref())
                .id(getId())
                .type(getType())
                .uri(getUri());
        builder.displayName = internalGetDisplayName();
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaylistOwnerObject}.
     */
    public static class Builder {
        private ExternalUrlObject externalUrls;
        private FollowersObject followers;
        private String href;
        private String id;
        private Type4 type;
        private String uri;
        private OptionalNullable<String> displayName;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for externalUrls.
         * @param  externalUrls  ExternalUrlObject value for externalUrls.
         * @return Builder
         */
        public Builder externalUrls(ExternalUrlObject externalUrls) {
            this.externalUrls = externalUrls;
            return this;
        }

        /**
         * Setter for followers.
         * @param  followers  FollowersObject value for followers.
         * @return Builder
         */
        public Builder followers(FollowersObject followers) {
            this.followers = followers;
            return this;
        }

        /**
         * Setter for href.
         * @param  href  String value for href.
         * @return Builder
         */
        public Builder href(String href) {
            this.href = href;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for type.
         * @param  type  Type4 value for type.
         * @return Builder
         */
        public Builder type(Type4 type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for uri.
         * @param  uri  String value for uri.
         * @return Builder
         */
        public Builder uri(String uri) {
            this.uri = uri;
            return this;
        }

        /**
         * Setter for displayName.
         * @param  displayName  String value for displayName.
         * @return Builder
         */
        public Builder displayName(String displayName) {
            this.displayName = OptionalNullable.of(displayName);
            return this;
        }

        /**
         * UnSetter for displayName.
         * @return Builder
         */
        public Builder unsetDisplayName() {
            displayName = null;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaylistOwnerObject} object using the set fields.
         * @return {@link PlaylistOwnerObject}
         */
        public PlaylistOwnerObject build() {
            PlaylistOwnerObject model =
                    new PlaylistOwnerObject(externalUrls, followers, href, id, type, uri,
                            displayName);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
