/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.spotify.api.DateTimeHelper;
import com.spotify.api.models.containers.PlaylistTrackObjectTrack;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for PlaylistTrackObject type.
 */
public class PlaylistTrackObject {
    private LocalDateTime addedAt;
    private PlaylistUserObject addedBy;
    private Boolean isLocal;
    private PlaylistTrackObjectTrack track;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaylistTrackObject() {
    }

    /**
     * Initialization constructor.
     * @param  addedAt  LocalDateTime value for addedAt.
     * @param  addedBy  PlaylistUserObject value for addedBy.
     * @param  isLocal  Boolean value for isLocal.
     * @param  track  PlaylistTrackObjectTrack value for track.
     */
    public PlaylistTrackObject(
            LocalDateTime addedAt,
            PlaylistUserObject addedBy,
            Boolean isLocal,
            PlaylistTrackObjectTrack track) {
        this.addedAt = addedAt;
        this.addedBy = addedBy;
        this.isLocal = isLocal;
        this.track = track;
    }

    /**
     * Getter for AddedAt.
     * The date and time the track or episode was added. _**Note**: some very old playlists may
     * return `null` in this field._
     * @return Returns the LocalDateTime
     */
    @JsonGetter("added_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getAddedAt() {
        return addedAt;
    }

    /**
     * Setter for AddedAt.
     * The date and time the track or episode was added. _**Note**: some very old playlists may
     * return `null` in this field._
     * @param addedAt Value for LocalDateTime
     */
    @JsonSetter("added_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setAddedAt(LocalDateTime addedAt) {
        this.addedAt = addedAt;
    }

    /**
     * Getter for AddedBy.
     * @return Returns the PlaylistUserObject
     */
    @JsonGetter("added_by")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlaylistUserObject getAddedBy() {
        return addedBy;
    }

    /**
     * Setter for AddedBy.
     * @param addedBy Value for PlaylistUserObject
     */
    @JsonSetter("added_by")
    public void setAddedBy(PlaylistUserObject addedBy) {
        this.addedBy = addedBy;
    }

    /**
     * Getter for IsLocal.
     * Whether this track or episode is a [local
     * file](https://developer.spotify.com/documentation/web-api/concepts/playlists/#local-files) or
     * not.
     * @return Returns the Boolean
     */
    @JsonGetter("is_local")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getIsLocal() {
        return isLocal;
    }

    /**
     * Setter for IsLocal.
     * Whether this track or episode is a [local
     * file](https://developer.spotify.com/documentation/web-api/concepts/playlists/#local-files) or
     * not.
     * @param isLocal Value for Boolean
     */
    @JsonSetter("is_local")
    public void setIsLocal(Boolean isLocal) {
        this.isLocal = isLocal;
    }

    /**
     * Getter for Track.
     * Information about the track or episode.
     * @return Returns the PlaylistTrackObjectTrack
     */
    @JsonGetter("track")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public PlaylistTrackObjectTrack getTrack() {
        return track;
    }

    /**
     * Setter for Track.
     * Information about the track or episode.
     * @param track Value for PlaylistTrackObjectTrack
     */
    @JsonSetter("track")
    public void setTrack(PlaylistTrackObjectTrack track) {
        this.track = track;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaylistTrackObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaylistTrackObject [" + "addedAt=" + addedAt + ", addedBy=" + addedBy
                + ", isLocal=" + isLocal + ", track=" + track + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlaylistTrackObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaylistTrackObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .addedAt(getAddedAt())
                .addedBy(getAddedBy())
                .isLocal(getIsLocal())
                .track(getTrack());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaylistTrackObject}.
     */
    public static class Builder {
        private LocalDateTime addedAt;
        private PlaylistUserObject addedBy;
        private Boolean isLocal;
        private PlaylistTrackObjectTrack track;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for addedAt.
         * @param  addedAt  LocalDateTime value for addedAt.
         * @return Builder
         */
        public Builder addedAt(LocalDateTime addedAt) {
            this.addedAt = addedAt;
            return this;
        }

        /**
         * Setter for addedBy.
         * @param  addedBy  PlaylistUserObject value for addedBy.
         * @return Builder
         */
        public Builder addedBy(PlaylistUserObject addedBy) {
            this.addedBy = addedBy;
            return this;
        }

        /**
         * Setter for isLocal.
         * @param  isLocal  Boolean value for isLocal.
         * @return Builder
         */
        public Builder isLocal(Boolean isLocal) {
            this.isLocal = isLocal;
            return this;
        }

        /**
         * Setter for track.
         * @param  track  PlaylistTrackObjectTrack value for track.
         * @return Builder
         */
        public Builder track(PlaylistTrackObjectTrack track) {
            this.track = track;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaylistTrackObject} object using the set fields.
         * @return {@link PlaylistTrackObject}
         */
        public PlaylistTrackObject build() {
            PlaylistTrackObject model =
                    new PlaylistTrackObject(addedAt, addedBy, isLocal, track);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
