/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for PlaylistsFollowersRequest type.
 */
public class PlaylistsFollowersRequest {
    private Boolean mPublic;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public PlaylistsFollowersRequest() {
    }

    /**
     * Initialization constructor.
     * @param  mPublic  Boolean value for mPublic.
     */
    public PlaylistsFollowersRequest(
            Boolean mPublic) {
        this.mPublic = mPublic;
    }

    /**
     * Getter for Public.
     * Defaults to `true`. If `true` the playlist will be included in user's public playlists, if
     * `false` it will remain private.
     * @return Returns the Boolean
     */
    @JsonGetter("public")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getPublic() {
        return mPublic;
    }

    /**
     * Setter for Public.
     * Defaults to `true`. If `true` the playlist will be included in user's public playlists, if
     * `false` it will remain private.
     * @param mPublic Value for Boolean
     */
    @JsonSetter("public")
    public void setPublic(Boolean mPublic) {
        this.mPublic = mPublic;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this PlaylistsFollowersRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaylistsFollowersRequest [" + "mPublic=" + mPublic + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link PlaylistsFollowersRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaylistsFollowersRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .mPublic(getPublic());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link PlaylistsFollowersRequest}.
     */
    public static class Builder {
        private Boolean mPublic;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for mPublic.
         * @param  mPublic  Boolean value for mPublic.
         * @return Builder
         */
        public Builder mPublic(Boolean mPublic) {
            this.mPublic = mPublic;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link PlaylistsFollowersRequest} object using the set fields.
         * @return {@link PlaylistsFollowersRequest}
         */
        public PlaylistsFollowersRequest build() {
            PlaylistsFollowersRequest model =
                    new PlaylistsFollowersRequest(mPublic);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
