/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for RecommendationsObject type.
 */
public class RecommendationsObject {
    private List<RecommendationSeedObject> seeds;
    private List<TrackObject> tracks;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public RecommendationsObject() {
    }

    /**
     * Initialization constructor.
     * @param  seeds  List of RecommendationSeedObject value for seeds.
     * @param  tracks  List of TrackObject value for tracks.
     */
    public RecommendationsObject(
            List<RecommendationSeedObject> seeds,
            List<TrackObject> tracks) {
        this.seeds = seeds;
        this.tracks = tracks;
    }

    /**
     * Getter for Seeds.
     * An array of recommendation seed objects.
     * @return Returns the List of RecommendationSeedObject
     */
    @JsonGetter("seeds")
    public List<RecommendationSeedObject> getSeeds() {
        return seeds;
    }

    /**
     * Setter for Seeds.
     * An array of recommendation seed objects.
     * @param seeds Value for List of RecommendationSeedObject
     */
    @JsonSetter("seeds")
    public void setSeeds(List<RecommendationSeedObject> seeds) {
        this.seeds = seeds;
    }

    /**
     * Getter for Tracks.
     * An array of track objects ordered according to the parameters supplied.
     * @return Returns the List of TrackObject
     */
    @JsonGetter("tracks")
    public List<TrackObject> getTracks() {
        return tracks;
    }

    /**
     * Setter for Tracks.
     * An array of track objects ordered according to the parameters supplied.
     * @param tracks Value for List of TrackObject
     */
    @JsonSetter("tracks")
    public void setTracks(List<TrackObject> tracks) {
        this.tracks = tracks;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this RecommendationsObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RecommendationsObject [" + "seeds=" + seeds + ", tracks=" + tracks
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link RecommendationsObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RecommendationsObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(seeds, tracks);
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link RecommendationsObject}.
     */
    public static class Builder {
        private List<RecommendationSeedObject> seeds;
        private List<TrackObject> tracks;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  seeds  List of RecommendationSeedObject value for seeds.
         * @param  tracks  List of TrackObject value for tracks.
         */
        public Builder(List<RecommendationSeedObject> seeds, List<TrackObject> tracks) {
            this.seeds = seeds;
            this.tracks = tracks;
        }

        /**
         * Setter for seeds.
         * @param  seeds  List of RecommendationSeedObject value for seeds.
         * @return Builder
         */
        public Builder seeds(List<RecommendationSeedObject> seeds) {
            this.seeds = seeds;
            return this;
        }

        /**
         * Setter for tracks.
         * @param  tracks  List of TrackObject value for tracks.
         * @return Builder
         */
        public Builder tracks(List<TrackObject> tracks) {
            this.tracks = tracks;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link RecommendationsObject} object using the set fields.
         * @return {@link RecommendationsObject}
         */
        public RecommendationsObject build() {
            RecommendationsObject model =
                    new RecommendationsObject(seeds, tracks);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
