/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.spotify.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for SavedTrackObject type.
 */
public class SavedTrackObject {
    private LocalDateTime addedAt;
    private TrackObject track;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SavedTrackObject() {
    }

    /**
     * Initialization constructor.
     * @param  addedAt  LocalDateTime value for addedAt.
     * @param  track  TrackObject value for track.
     */
    public SavedTrackObject(
            LocalDateTime addedAt,
            TrackObject track) {
        this.addedAt = addedAt;
        this.track = track;
    }

    /**
     * Getter for AddedAt.
     * The date and time the track was saved. Timestamps are returned in ISO 8601 format as
     * Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ. If the time is
     * imprecise (for example, the date/time of an album release), an additional field indicates the
     * precision; see for example, release_date in an album object.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("added_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getAddedAt() {
        return addedAt;
    }

    /**
     * Setter for AddedAt.
     * The date and time the track was saved. Timestamps are returned in ISO 8601 format as
     * Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ. If the time is
     * imprecise (for example, the date/time of an album release), an additional field indicates the
     * precision; see for example, release_date in an album object.
     * @param addedAt Value for LocalDateTime
     */
    @JsonSetter("added_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setAddedAt(LocalDateTime addedAt) {
        this.addedAt = addedAt;
    }

    /**
     * Getter for Track.
     * @return Returns the TrackObject
     */
    @JsonGetter("track")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public TrackObject getTrack() {
        return track;
    }

    /**
     * Setter for Track.
     * @param track Value for TrackObject
     */
    @JsonSetter("track")
    public void setTrack(TrackObject track) {
        this.track = track;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SavedTrackObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SavedTrackObject [" + "addedAt=" + addedAt + ", track=" + track
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SavedTrackObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SavedTrackObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .addedAt(getAddedAt())
                .track(getTrack());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SavedTrackObject}.
     */
    public static class Builder {
        private LocalDateTime addedAt;
        private TrackObject track;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for addedAt.
         * @param  addedAt  LocalDateTime value for addedAt.
         * @return Builder
         */
        public Builder addedAt(LocalDateTime addedAt) {
            this.addedAt = addedAt;
            return this;
        }

        /**
         * Setter for track.
         * @param  track  TrackObject value for track.
         * @return Builder
         */
        public Builder track(TrackObject track) {
            this.track = track;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SavedTrackObject} object using the set fields.
         * @return {@link SavedTrackObject}
         */
        public SavedTrackObject build() {
            SavedTrackObject model =
                    new SavedTrackObject(addedAt, track);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
