/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.spotify.api.DateTimeHelper;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.time.LocalDateTime;
import java.util.Map;

/**
 * This is a model class for SavedEpisodeObject type.
 */
public class SavedEpisodeObject {
    private LocalDateTime addedAt;
    private EpisodeObject episode;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public SavedEpisodeObject() {
    }

    /**
     * Initialization constructor.
     * @param  addedAt  LocalDateTime value for addedAt.
     * @param  episode  EpisodeObject value for episode.
     */
    public SavedEpisodeObject(
            LocalDateTime addedAt,
            EpisodeObject episode) {
        this.addedAt = addedAt;
        this.episode = episode;
    }

    /**
     * Getter for AddedAt.
     * The date and time the episode was saved. Timestamps are returned in ISO 8601 format as
     * Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("added_at")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getAddedAt() {
        return addedAt;
    }

    /**
     * Setter for AddedAt.
     * The date and time the episode was saved. Timestamps are returned in ISO 8601 format as
     * Coordinated Universal Time (UTC) with a zero offset: YYYY-MM-DDTHH:MM:SSZ.
     * @param addedAt Value for LocalDateTime
     */
    @JsonSetter("added_at")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setAddedAt(LocalDateTime addedAt) {
        this.addedAt = addedAt;
    }

    /**
     * Getter for Episode.
     * @return Returns the EpisodeObject
     */
    @JsonGetter("episode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EpisodeObject getEpisode() {
        return episode;
    }

    /**
     * Setter for Episode.
     * @param episode Value for EpisodeObject
     */
    @JsonSetter("episode")
    public void setEpisode(EpisodeObject episode) {
        this.episode = episode;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this SavedEpisodeObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SavedEpisodeObject [" + "addedAt=" + addedAt + ", episode=" + episode
                + ", additionalProperties=" + additionalProperties + "]";
    }

    /**
     * Builds a new {@link SavedEpisodeObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SavedEpisodeObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .addedAt(getAddedAt())
                .episode(getEpisode());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link SavedEpisodeObject}.
     */
    public static class Builder {
        private LocalDateTime addedAt;
        private EpisodeObject episode;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for addedAt.
         * @param  addedAt  LocalDateTime value for addedAt.
         * @return Builder
         */
        public Builder addedAt(LocalDateTime addedAt) {
            this.addedAt = addedAt;
            return this;
        }

        /**
         * Setter for episode.
         * @param  episode  EpisodeObject value for episode.
         * @return Builder
         */
        public Builder episode(EpisodeObject episode) {
            this.episode = episode;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link SavedEpisodeObject} object using the set fields.
         * @return {@link SavedEpisodeObject}
         */
        public SavedEpisodeObject build() {
            SavedEpisodeObject model =
                    new SavedEpisodeObject(addedAt, episode);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
