/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.List;
import java.util.Map;

/**
 * This is a model class for StartOrResumePlaybackRequest type.
 */
public class StartOrResumePlaybackRequest {
    private String contextUri;
    private List<String> uris;
    private Object offset;
    private Integer positionMs;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public StartOrResumePlaybackRequest() {
    }

    /**
     * Initialization constructor.
     * @param  contextUri  String value for contextUri.
     * @param  uris  List of String value for uris.
     * @param  offset  Object value for offset.
     * @param  positionMs  Integer value for positionMs.
     */
    public StartOrResumePlaybackRequest(
            String contextUri,
            List<String> uris,
            Object offset,
            Integer positionMs) {
        this.contextUri = contextUri;
        this.uris = uris;
        this.offset = offset;
        this.positionMs = positionMs;
    }

    /**
     * Getter for ContextUri.
     * Optional. Spotify URI of the context to play. Valid contexts are albums, artists &amp; playlists.
     * `{context_uri:"spotify:album:1Je1IMUlBXcx1Fz0WE7oPT"}`
     * @return Returns the String
     */
    @JsonGetter("context_uri")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getContextUri() {
        return contextUri;
    }

    /**
     * Setter for ContextUri.
     * Optional. Spotify URI of the context to play. Valid contexts are albums, artists &amp; playlists.
     * `{context_uri:"spotify:album:1Je1IMUlBXcx1Fz0WE7oPT"}`
     * @param contextUri Value for String
     */
    @JsonSetter("context_uri")
    public void setContextUri(String contextUri) {
        this.contextUri = contextUri;
    }

    /**
     * Getter for Uris.
     * Optional. A JSON array of the Spotify track URIs to play. For example: `{"uris":
     * ["spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "spotify:track:1301WleyT98MSxVHPZCA6M"]}`
     * @return Returns the List of String
     */
    @JsonGetter("uris")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getUris() {
        return uris;
    }

    /**
     * Setter for Uris.
     * Optional. A JSON array of the Spotify track URIs to play. For example: `{"uris":
     * ["spotify:track:4iV5W9uYEdYUVa79Axb7Rh", "spotify:track:1301WleyT98MSxVHPZCA6M"]}`
     * @param uris Value for List of String
     */
    @JsonSetter("uris")
    public void setUris(List<String> uris) {
        this.uris = uris;
    }

    /**
     * Getter for Offset.
     * Optional. Indicates from where in the context playback should start. Only available when
     * context_uri corresponds to an album or playlist object "position" is zero based and can’t be
     * negative. Example: `"offset": {"position": 5}` "uri" is a string representing the uri of the
     * item to start at. Example: `"offset": {"uri": "spotify:track:1301WleyT98MSxVHPZCA6M"}`
     * @return Returns the Object
     */
    @JsonGetter("offset")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Object getOffset() {
        return offset;
    }

    /**
     * Setter for Offset.
     * Optional. Indicates from where in the context playback should start. Only available when
     * context_uri corresponds to an album or playlist object "position" is zero based and can’t be
     * negative. Example: `"offset": {"position": 5}` "uri" is a string representing the uri of the
     * item to start at. Example: `"offset": {"uri": "spotify:track:1301WleyT98MSxVHPZCA6M"}`
     * @param offset Value for Object
     */
    @JsonSetter("offset")
    public void setOffset(Object offset) {
        this.offset = offset;
    }

    /**
     * Getter for PositionMs.
     * Indicates from what position to start playback. Must be a positive number. Passing in a
     * position that is greater than the length of the track will cause the player to start playing
     * the next song.
     * @return Returns the Integer
     */
    @JsonGetter("position_ms")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getPositionMs() {
        return positionMs;
    }

    /**
     * Setter for PositionMs.
     * Indicates from what position to start playback. Must be a positive number. Passing in a
     * position that is greater than the length of the track will cause the player to start playing
     * the next song.
     * @param positionMs Value for Integer
     */
    @JsonSetter("position_ms")
    public void setPositionMs(Integer positionMs) {
        this.positionMs = positionMs;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this StartOrResumePlaybackRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "StartOrResumePlaybackRequest [" + "contextUri=" + contextUri + ", uris=" + uris
                + ", offset=" + offset + ", positionMs=" + positionMs + ", additionalProperties="
                + additionalProperties + "]";
    }

    /**
     * Builds a new {@link StartOrResumePlaybackRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link StartOrResumePlaybackRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .contextUri(getContextUri())
                .uris(getUris())
                .offset(getOffset())
                .positionMs(getPositionMs());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link StartOrResumePlaybackRequest}.
     */
    public static class Builder {
        private String contextUri;
        private List<String> uris;
        private Object offset;
        private Integer positionMs;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for contextUri.
         * @param  contextUri  String value for contextUri.
         * @return Builder
         */
        public Builder contextUri(String contextUri) {
            this.contextUri = contextUri;
            return this;
        }

        /**
         * Setter for uris.
         * @param  uris  List of String value for uris.
         * @return Builder
         */
        public Builder uris(List<String> uris) {
            this.uris = uris;
            return this;
        }

        /**
         * Setter for offset.
         * @param  offset  Object value for offset.
         * @return Builder
         */
        public Builder offset(Object offset) {
            this.offset = offset;
            return this;
        }

        /**
         * Setter for positionMs.
         * @param  positionMs  Integer value for positionMs.
         * @return Builder
         */
        public Builder positionMs(Integer positionMs) {
            this.positionMs = positionMs;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link StartOrResumePlaybackRequest} object using the set fields.
         * @return {@link StartOrResumePlaybackRequest}
         */
        public StartOrResumePlaybackRequest build() {
            StartOrResumePlaybackRequest model =
                    new StartOrResumePlaybackRequest(contextUri, uris, offset, positionMs);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
