/*
 * SpotifyWebApiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.spotify.api.models;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.core.types.AdditionalProperties;
import io.apimatic.core.utilities.ConversionHelper;
import java.util.Map;

/**
 * This is a model class for TimeIntervalObject type.
 */
public class TimeIntervalObject {
    private Double start;
    private Double duration;
    private Double confidence;
    private AdditionalProperties<Object> additionalProperties = 
            new AdditionalProperties<Object>(this.getClass());

    /**
     * Default constructor.
     */
    public TimeIntervalObject() {
    }

    /**
     * Initialization constructor.
     * @param  start  Double value for start.
     * @param  duration  Double value for duration.
     * @param  confidence  Double value for confidence.
     */
    public TimeIntervalObject(
            Double start,
            Double duration,
            Double confidence) {
        this.start = start;
        this.duration = duration;
        this.confidence = confidence;
    }

    /**
     * Getter for Start.
     * The starting point (in seconds) of the time interval.
     * @return Returns the Double
     */
    @JsonGetter("start")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getStart() {
        return start;
    }

    /**
     * Setter for Start.
     * The starting point (in seconds) of the time interval.
     * @param start Value for Double
     */
    @JsonSetter("start")
    public void setStart(Double start) {
        this.start = start;
    }

    /**
     * Getter for Duration.
     * The duration (in seconds) of the time interval.
     * @return Returns the Double
     */
    @JsonGetter("duration")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getDuration() {
        return duration;
    }

    /**
     * Setter for Duration.
     * The duration (in seconds) of the time interval.
     * @param duration Value for Double
     */
    @JsonSetter("duration")
    public void setDuration(Double duration) {
        this.duration = duration;
    }

    /**
     * Getter for Confidence.
     * The confidence, from 0.0 to 1.0, of the reliability of the interval.
     * @return Returns the Double
     */
    @JsonGetter("confidence")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Double getConfidence() {
        return confidence;
    }

    /**
     * Setter for Confidence.
     * The confidence, from 0.0 to 1.0, of the reliability of the interval.
     * @param confidence Value for Double
     */
    @JsonSetter("confidence")
    public void setConfidence(Double confidence) {
        this.confidence = confidence;
    }

    /**
     * Hidden method for the serialization of additional properties.
     * @return The map of additionally set properties.
     */
    @JsonAnyGetter
    private Map<String, Object> getAdditionalProperties() {
        return additionalProperties.getAdditionalProperties();
    }

    /**
     * Hidden method for the de-serialization of additional properties.
     * @param name The name of the additional property.
     * @param value The Object value of the additional property.
     */
    @JsonAnySetter
    private void setAdditionalProperties(String name, Object value) {
        additionalProperties.setAdditionalProperty(name,
                ConversionHelper.convertToSimpleType(value,
                        x -> x),
                true);
    }

    /**
     * Getter for the value of additional properties based on provided property name.
     * @param name The name of the additional property.
     * @return Either the Object property value or null if not exist.
     */
    
    public Object getAdditionalProperty(String name) {
        return additionalProperties.getAdditionalProperty(name);
    }

    /**
     * Converts this TimeIntervalObject into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "TimeIntervalObject [" + "start=" + start + ", duration=" + duration
                + ", confidence=" + confidence + ", additionalProperties=" + additionalProperties
                + "]";
    }

    /**
     * Builds a new {@link TimeIntervalObject.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link TimeIntervalObject.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .start(getStart())
                .duration(getDuration())
                .confidence(getConfidence());
        builder.additionalProperties = additionalProperties;
        return builder;
    }

    /**
     * Class to build instances of {@link TimeIntervalObject}.
     */
    public static class Builder {
        private Double start;
        private Double duration;
        private Double confidence;
        private AdditionalProperties<Object> additionalProperties =
                new AdditionalProperties<Object>();



        /**
         * Setter for start.
         * @param  start  Double value for start.
         * @return Builder
         */
        public Builder start(Double start) {
            this.start = start;
            return this;
        }

        /**
         * Setter for duration.
         * @param  duration  Double value for duration.
         * @return Builder
         */
        public Builder duration(Double duration) {
            this.duration = duration;
            return this;
        }

        /**
         * Setter for confidence.
         * @param  confidence  Double value for confidence.
         * @return Builder
         */
        public Builder confidence(Double confidence) {
            this.confidence = confidence;
            return this;
        }

        /**
         * Setter for additional property that are not in model fields.
         * @param name The name of the additional property.
         * @param value The Object value of the additional property.
         * @return Builder.
         */
        public Builder additionalProperty(String name, Object value) {
            this.additionalProperties.setAdditionalProperty(name, value);
            return this;
        }

        /**
         * Builds a new {@link TimeIntervalObject} object using the set fields.
         * @return {@link TimeIntervalObject}
         */
        public TimeIntervalObject build() {
            TimeIntervalObject model =
                    new TimeIntervalObject(start, duration, confidence);
            model.additionalProperties = additionalProperties;
            return model;
        }
    }
}
